```{r}
covid_cases_cleaned = read.csv("https://www.dropbox.com/s/ttj2bfdmspfsiw7/covid-cases-deaths-cleaned.csv?dl=1")

hospital_cleaned = read.csv("https://www.dropbox.com/s/worwm4rnh8mu7tj/patient-impact-hospital-capacity-cleaned.csv?dl=1")

places_cleaned = read.csv("https://www.dropbox.com/s/wqz4xrir84g60qy/places-project-chronic-diseases-cleaned.csv?dl=1")

vaccination_cleaned = read.csv("https://www.dropbox.com/s/bj9xofn2ctmtjtj/us_vaccination-cleaned.csv?dl=1")

demographics_cleaned = read.csv("https://www.dropbox.com/s/b5o11qew0d899p3/demographic-final.csv?dl=1")

economics_cleaned = read.csv("https://www.dropbox.com/s/hvtlxdspndnxizs/economic-characteristics-cleaned.csv?dl=1")

#renaming key to be "fips code" across all tables
covid_cases_cleaned <- rename(covid_cases_cleaned, "fips_code" = "fips")
places_cleaned <- rename(places_cleaned, "fips_code" = "fips")
demographics_cleaned <- rename(demographics_cleaned, "fips_code" = "fips")
vaccination_cleaned <- rename(vaccination_cleaned, "fips_code" = "FIPS")
economics_cleaned <- rename(economics_cleaned, "fips_code" = "Fips")

#converting fips code to integers
covid_cases_cleaned$fips_code <- as.integer(covid_cases_cleaned$fips_code)
hospital_cleaned$fips_code <- as.integer(hospital_cleaned$fips_code)
places_cleaned$fips_code <- as.integer(places_cleaned$fips_code)
vaccination_cleaned$fips_code <- as.integer(vaccination_cleaned$fips_code)
demographics_cleaned$fips_code <- as.integer(demographics_cleaned$fips_code)
economics_cleaned$fips_code <- as.integer(economics_cleaned$fips_code)

```

## performing antijoin
```{r}
library(dplyr)
two_anti_join <- anti_join(covid_cases_cleaned, hospital_cleaned, by = "fips_code")

three_anti_join <- anti_join(two_anti_join, places_cleaned, by = "fips_code")

four_anti_join <- anti_join(three_anti_join, vaccination_cleaned, by = "fips_code")

five_anti_join <- anti_join(four_anti_join, demographics_cleaned, by = "fips_code")

six_anti_join <- anti_join(five_anti_join, economics_cleaned, by = "fips_code")


```

