```{r}
# Package prep
require(tidyr)
require(dplyr)
require(readr)
require(mosaic)
require(ggplot2)
require(reshape2)

# https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh
us.vaccination <- read_csv("https://www.dropbox.com/s/87vdc7kjvkqa6ca/COVID-19_Vaccinations_in_the_United_States_County.csv?dl=1")

colnames(us.vaccination)[1:2] <- c("date", "fips")
us.vaccination <- us.vaccination[!is.na(us.vaccination$fips), ]

us.vaccination$fips <- as.integer(us.vaccination$fips)
```

```{r}

# load required libraries
library(ggplot2)
library(dplyr)

# plot histogram of completeness percentage
ggplot(us.vaccination, aes(x = Completeness_pct)) + 
  geom_histogram() + 
  ggtitle("Histogram of Data Completeness Percentage")

# plot scatter plot of administered doses versus completeness percentage
ggplot(us.vaccination, aes(x = Series_Complete_65PlusPop_Pct, y = Administered_Dose1_Recip)) +
  geom_point() +
  ggtitle("Scatter plot of Series Complete 65PlusPop Pct versus Administered Doses")

# plot bar chart of administered doses for each state
us.vaccination %>%
  group_by(Recip_State) %>%
  summarise(total_doses = sum(Administered_Dose1_Recip)) %>%
  ggplot(aes(x = Recip_State, y = total_doses)) +
  geom_col() +
  ggtitle("Total Administered Doses by State")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


