```{r}
# Package prep
require(tidyr)
require(dplyr)
require(tibble)
require(readr)
require(mosaic)
require(ggplot2)
require(reshape2)

# COVID-19 Reported Patient Impact and Hospital Capacity by Facility: https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/anag-cw7u
# COVID-19 Reported Patient Impact and Hospital Capacity by Facility (data source): https://healthdata.gov/stories/s/nhgk-5gpv
patientImpact.hospitalCapacity <- read_csv("https://www.dropbox.com/s/fgb0ga3o84bfajp/covid-19_reported_patient_impact_and_hospital_capacity_by_facility.csv?dl=1")
View(patientImpact.hospitalCapacity)

patientImpact.hospitalCapacity$collection_week <- as.Date(patientImpact.hospitalCapacity$collection_week)
class(patientImpact.hospitalCapacity$collection_week)

week_number <- strftime(patientImpact.hospitalCapacity$collection_week, format = "%V")
patientImpact.hospitalCapacity <- add_column(patientImpact.hospitalCapacity, 
                                             week_number, .after = 1)
patientImpact.hospitalCapacity <- na.omit(patientImpact.hospitalCapacity)

View(patientImpact.hospitalCapacity)
```

```{r}
# Load required libraries
library(ggplot2)
library(dplyr)

# Create a stacked bar plot of hospital_subtype by is_metro_micro
patientImpact.hospitalCapacity %>% 
  group_by(is_metro_micro, hospital_subtype) %>%
  summarize(count = n()) %>%
  ggplot(aes(x = is_metro_micro, y = count, fill = hospital_subtype)) +
  geom_col() +
  labs(x = "Is hospital in a metro/micro area?", y = "Count", fill = "Hospital Subtype")

```


