---
title: "Regression Modeling"
author: "Group Healthcare Crisis"
date: "`r Sys.Date()`"
output: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# Package prep
require(tidyr)
require(dplyr)
require(tibble)
require(readr)
require(mosaic)
require(ggplot2)
require(reshape2)
require(leaps)
require(lubridate)
library(corrplot)
library(leaps)
library(MASS)
library(openxlsx)

# Data prep
data <- read_csv("https://www.dropbox.com/s/nolym5vik4je3yu/final_merged_data.csv?dl=1")
```
## Data

```{r}
reduced <- data
reduced <- dplyr::select(data, -c(fips, week, cases, deaths, black, hispanic, native, asian, white))
```

## Correlation Plot

```{r}
plot.new()
dev.off()

# Select all columns except "CFR"
data_clean_without_CFR <- na.omit(reduced[, !colnames(reduced) %in% "CFR"])

# Compute the correlation matrix
mycorr <- cor(data_clean_without_CFR)

# Plot the correlation matrix
# corrplot(mycorr, type = "upper", order = "hclust", tl.col = "black", tl.cex = 0.45, method="shade")
colnames(mycorr) <- rownames(mycorr) <- as.character(1:35)
png("/Users/cameronlian/Desktop/corrplot.png", width = 1920, height = 1080)
corrplot(mycorr, type = "upper", method = "shade", 
         tl.srt = 45, tl.col = "black", tl.cex = 1.5, 
         cl.cex = 2, cl.ratio = 0.15, cl.offset = 0.5, 
         addgrid.col = "black", bg = "black")
dev.off()

write.csv(data.frame(colnames(data_clean_without_CFR)),
          "/Users/cameronlian/Desktop/column_names.csv", 
          row.names = FALSE)
```

## Pairs Plot

```{r}
ncol(data)

# Set the plot margins to a smaller value
par(mar = c(0.002, 0.002, 0.002, 0.002))

# Create the pairs plot
pairs(data[,1:36], main = "Pairs plot of 36 columns of data")

# Create a pairs plot
pairs(data, main = "Pairs Plot for Covid 2021 Data Set")
```




## Subset regression

```{r}
## Dividing the large dataset
half1 <- data_clean_without_CFR[, 1:17]
half1 <- cbind(data_clean$CFR, half1)
colnames(half1)[colnames(half1) == "data_clean$CFR"] <- "CFR"

half2 <- data_clean_without_CFR[, 18:ncol(data_clean_without_CFR)]
half2 <- cbind(data_clean$CFR, half2)
colnames(half2)[colnames(half2) == "data_clean$CFR"] <- "CFR"


# Load the "leaps" package
library(leaps)

# Perform best subsets regression on dataset 1
best_subsets1 <- regsubsets(CFR ~ ., data = half1, nvmax = ncol(half1)-1, method = "exhaustive")
summary(best_subsets1, rsq = TRUE)

# Perform best subsets regression on dataset 2
best_subsets2 <- regsubsets(CFR ~ ., data = half2, nvmax = ncol(half2)-1, method = "exhaustive")
summary(best_subsets2, rsq = TRUE)

#best_1.lm = leaps(half1,half1$CFR, method = 'adjr2', names = names(half1), nbest = 3)



#library(dplyr)

#subsetdf <- dplyr::select(df_nw, CFR, pop_over_65, population, housing_units, male, under18, commute, 
 #                   income_below_poverty, health_insur_coverage, household_income, 
  #                  edu_health_social_industry, staffed_icu_adult_patients_confirmed_covid_7_day_avg,
   #                 cancer, casthma, chd, copd, csmoking, diabetes, highchol, lpa, obesity)

```

```{r}
require(stringr)

png("/Users/cameronlian/Desktop/best-subsets1.png", width = 1920, height = 1080)
par(mar = c(10, 2, 2, 1))
plot(best_subsets1, scale = "adjr2")
"pop_over_65"
"under18"
"commute"
"health_insur_coverage"
"household_income"
"male"
"income_below_poverty"
"total_staffed_adult_icu_beds_7_day_avg"

# png("/Users/cameronlian/Desktop/best-subsets2.png", width = 1920, height = 1080)
plot(best_subsets2, scale = "adjr2")
"staffed_icu_adult_patients_confirmed_covid_7_day_avg"
"binge"
"casthma"
"chd"
"csmoking"
"diabetes"
"lpa"
"obesity"
"Administered_Dose1_Pop_Pct"

```

```{r}
# Plot the R-squared values for dataset 1
plot(best_subsets1$rsq, xlab = "Number of predictors", ylab = "R-squared", main = "Best subsets regression for dataset 1")

# Add text labels for the best models
text(which.max(best_subsets1$rsq), max(best_subsets1$rsq), paste0("Best model: ", which.max(best_subsets1$rsq), " predictors"))

# Plot the R-squared values for dataset 2
plot(best_subsets2$rsq, xlab = "Number of predictors", ylab = "R-squared", main = "Best subsets regression for dataset 2")

# Add text labels for the best models
text(which.max(best_subsets2$rsq), max(best_subsets2$rsq), paste0("Best model: ", which.max(best_subsets2$rsq), " predictors"))

```

## Best Subsets

```{r}
# perform best subsets regression with up to 3 predictors
best.lm <- leaps(subsetdf, subsetdf$CFR, method = "adjr2", names = c("pop_over_65", "population", "housing_units", "male", "under18", "commute", 
                 "income_below_poverty", "health_insur_coverage", "household_income", 
                    "edu_health_social_industry", "staffed_icu_adult_patients_confirmed_covid_7_day_avg",
                    "cancer", "casthma", "chd", "copd", "csmoking", "diabetes", "highchol", "lpa", "obesity"), nbest=3)

model <- regsubsets(CFR ~ ., data=subsetdf, nvmax=20)

# summarize the results
summary(model)

# plot the results
plot(model, scale="adjr2")
```

## Variance inflation factor (VIF)
```{r}
require(dplyr)
new_data <- data_clean %>% 
  select(CFR, staffed_icu_adult_patients_confirmed_covid_7_day_avg, 
         binge, chd, csmoking, diabetes, lpa, pop_over_65, under18, 
         commute, health_insur_coverage, male)
```
