---
title: "Regression Modeling"
author: "Group Healthcare Crisis"
date: "`r Sys.Date()`"
output: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# Package prep
require(tidyr)
require(dplyr)
require(tibble)
require(readr)
require(mosaic)
require(ggplot2)
require(reshape2)
require(leaps)
require(lubridate)
library(corrplot)
library(leaps)
library(MASS)
library(openxlsx)

# Data prep
new_combined_2021 <- read_csv("https://www.dropbox.com/s/nolym5vik4je3yu/final_merged_data.csv?dl=1")
```

## Dividing the large dataset

```{r}
# Splitting the original data frame into halves
# half <- ncol(new_combined_2021) %/% 2 + 4
# new_combined_1 <- new_combined_2021[, c(1:4, 5:half)]
# new_combined_2 <- new_combined_2021[, c(1:4, (half+1):ncol(new_combined_2021))]
# View(new_combined_1)
# View(new_combined_2)

# Moving CFR to the fourth row
# new_combined_2021 <- new_combined_2021 %>% 
#   select(1:3, CFR, everything())

new_combined_2021$cases <- NULL
new_combined_2021$deaths <- NULL
new_combined_2021 <- new_combined_2021[, -c(8:11)]

df_nw <- new_combined_2021
df_nw$white <- NULL # white variable is excluded in df_nw
View(df_nw)

# Splitting into four smaller data frames
# Determine the number of splits and the size of each split
ncol(df_nw)
constant <- df_nw[3:3]
half_1 <- df_nw[4:17]
half_2 <- df_nw[18:38]
half_1 <- cbind(constant, half_1)
half_2 <- cbind(constant, half_2)
```

## Stepwise regression

```{r}
fit_nw <- lm(CFR ~ ., data = df_nw[, -(1:2)])
step_nw <- stepAIC(fit_nw, direction = "both")
summary_step <- summary(step_nw)
summary_step
View(summary_step$terms)
```

## Best subsets for quarter data sets
```{r}
bs_1 <- regsubsets(data = quarter_1, 
                   CFR ~ ., 
                   nbest = 1, 
                   nvmax = NULL, 
                   force.in = NULL, force.out = NULL, 
                   method = "exhaustive", 
                   really.big = T)
summary_bs_1 <- summary(bs_1)
as.data.frame(summary_bs_1$outmat)
numb_predictors_1 <- which.max(summary_bs_1$adjr2)
summary_bs_1$which[numb_predictors_1,]

bs_2 <- regsubsets(data = quarter_2, 
                   CFR ~ ., 
                   nbest = 1, 
                   nvmax = NULL, 
                   force.in = NULL, force.out = NULL, 
                   method = "exhaustive", 
                   really.big = T)
summary_bs_2 <- summary(bs_2)
as.data.frame(summary_bs_2$outmat)
numb_predictors_2 <- which.max(summary_bs_2$adjr2)
summary_bs_2$which[numb_predictors_2,]

bs_3 <- regsubsets(data = quarter_3, 
                   CFR ~ ., 
                   nbest = 1, 
                   nvmax = NULL, 
                   force.in = NULL, force.out = NULL, 
                   method = "exhaustive", 
                   really.big = T)
summary_bs_3 <- summary(bs_3)
as.data.frame(summary_bs_3$outmat)
numb_predictors_3 <- which.max(summary_bs_3$adjr2)
summary_bs_3$which[numb_predictors_3,]

bs_4 <- regsubsets(data = quarter_4, 
                   CFR ~ ., 
                   nbest = 1, 
                   nvmax = NULL, 
                   force.in = NULL, force.out = NULL, 
                   method = "exhaustive", 
                   really.big = T)
summary_bs_4 <- summary(bs_4)
as.data.frame(summary_bs_4$outmat)
numb_predictors_4 <- which.max(summary_bs_4$adjr2)
summary_bs_4$which[numb_predictors_4,]
```

## Best subsets for entire data set
```{r}
df_nw_clean <- df_nw[complete.cases(df_nw), ]

y <- df_nw_clean$CFR
x <- df_nw_clean[, c("pop_over_65", "population", "housing_units", "male", "under18", "commute",
                     "income_below_poverty", "health_insur_coverage", "household_income",
                     "edu_health_social_industry",
                     "all_adult_hospital_inpatient_bed_occupied_7_day_avg",
                     "total_adult_patients_hospitalized_confirmed_covid_7_day_avg",
                     "staffed_adult_icu_bed_occupancy_7_day_avg",
                     "binge", "casthma", "chd", "csmoking",
                     "diabetes", "highchol", "lpa", "obesity", "sleep",
                     "Completeness_pct", "Administered_Dose1_Pop_Pct",
                     "Booster_Doses_Vax_Pct",
                     "Series_Complete_Pop_Pct_SVI")]
x[] <- lapply(x, as.numeric)
y[] <- lapply(y, as.numeric)

result <- leaps(x = x, y = y, method = "adjr2", 
                names = c("pop_over_65", "population", "housing_units", "male", "under18", "commute",
                     "income_below_poverty", "health_insur_coverage", "household_income",
                     "edu_health_social_industry",
                     "all_adult_hospital_inpatient_bed_occupied_7_day_avg",
                     "total_adult_patients_hospitalized_confirmed_covid_7_day_avg",
                     "staffed_adult_icu_bed_occupancy_7_day_avg",
                     "binge", "casthma", "chd", "csmoking",
                     "diabetes", "highchol", "lpa", "obesity", "sleep",
                     "Completeness_pct", "Administered_Dose1_Pop_Pct",
                     "Booster_Doses_Vax_Pct",
                     "Series_Complete_Pop_Pct_SVI"), 
                nbest = 3)
bb_summary <- summary(result)
```

## Correlation plots
```{r, dev = "jpg"}
plot.new()
dev.off()

data_clean <- na.omit(df_nw)
corr <- cor(data_clean)
corrplot(corr, method = "color", type = "upper", order = "hclust", 
         tl.col = "black", tl.cex = 0.35, tl.srt = 45 ,tl.offset = 0.5, 
         cl.cex = 0.35, cl.ratio = 0.10, cl.offset = 0.5)
```

## Residual plot

## Pair plot
```{r}
par(mar=c(1,1,1,1))
pairs_1 <- pairs(half_1)
paris_2 <- pairs(half_2)
```

## Best subset regression of 20 variables from stepwise

```{r}

```
